#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Mar 01 08:41:39 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=5
shaderPack=Spooklementary_v2.0.4.zip
enableShaders=false
