#The http proxy host if not empty.Default: ""
http_proxy_host = ""
#The http port if http proxy host not empty.
#Range: > -2147483648
http_proxy_port = 0
#Maximum retries number in case of network error.
#Range: > 0
max_retries = 4
#The translator.(The default translator will only notice you to choose a translator.)
#Allowed Values: GOOGLE, LLM, DEFAULT
translator_type = "DEFAULT"
#The language you want to translate to.Should use Locale Code like "en_us".Default: zh_cn
target_language = "zh_cn"
#This mod use OpenAI API.The API endpoint URL for LLM service.Default: ""
llm_api_url = ""
#The API key of LLM API.Default: ""
llm_api_key = ""
#The model to use for translations.Default: ""
llm_model = ""
#The Json post to LLM API.DON'T modify it if you don't know what it is.
llm_post_content = "{\n    \"model\": \"${model}\",\n    ${modelConfig}\n    \"messages\": [\n        {\n            \"role\": \"system\",\n            \"content\": \"${systemPrompt}\"\n        },\n        {\n            \"role\": \"user\",\n            \"content\": \"${content}\"\n        }\n    ]\n}\n"
#The system prompt give to llm.Should contain %s to replace to target language.Default: Treat user content as plain text input and translate it into ${targetLanguage}, output translation ONLY. If translation is unnecessary (e.g. proper nouns, codes, etc.), return the original text. NO explanations. NO notes.
llm_system_prompt = "Treat user content as plain text input and translate it into ${targetLanguage}, output translation ONLY. If translation is unnecessary (e.g. proper nouns, codes, etc.), return the original text. NO explanations. NO notes."
#Json Elements to configure llm.The ending should be followed by a comma.Default: "temperature": 0,
llm_model_configuration = "\"temperature\": 0,"

